#!/bin/sh

export XDG_DATA_DIRS="/usr/local/share/:/usr/share/:/usr/share/gdm/:/var/lib/menu-xdg/"

if [ -z "$XDG_CONFIG_HOME" ]; then
	export XDG_CONFIG_HOME="$HOME/.config"
fi

# Ensure the existance of pcmanfm config file
PCMANFM_CONF_DIR="$XDG_CONFIG_HOME/pcmanfm/LDE"
if [ ! -f "$PCMANFM_CONF_DIR/pcmanfm.conf" ]; then
	mkdir -p "$PCMANFM_CONF_DIR"
	cp /etc/xdg/pcmanfm/LDE/pcmanfm.conf "$PCMANFM_CONF_DIR/pcmanfm.conf"
fi

# Ensure the existance of openbox config file
OPENBOX_CONF_DIR="$XDG_CONFIG_HOME/openbox"
if [ ! -f "$OPENBOX_CONF_DIR/lde-rc.xml" ]; then
	mkdir -p "$OPENBOX_CONF_DIR"
	cp /etc/xdg/openbox/LDE/rc.xml "$OPENBOX_CONF_DIR/lde-rc.xml"
fi

# Ensure the existance of lxpanel config files
LXPANEL_CONF_DIR="$XDG_CONFIG_HOME/lxpanel"
if [ ! -e "$LXPANEL_CONF_DIR/LDE" ]; then
	mkdir -p "$LXPANEL_CONF_DIR"
	cp -r /etc/xdg/lxpanel/profile/LDE "$LXPANEL_CONF_DIR"
fi

# Ensure the existance of the 'Desktop' folder
if [ -e "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
	. "$XDG_CONFIG_HOME/user-dirs.dirs"
else
	XDG_DESKTOP_DIR="$HOME/Desktop"
fi
mkdir -p "$XDG_DESKTOP_DIR"

# Clean up after GDM (GDM sets the number of desktops to one)
xprop -root -remove _NET_NUMBER_OF_DESKTOPS -remove _NET_DESKTOP_NAMES -remove _NET_CURRENT_DESKTOP 2> /dev/null

# Enable GTK+2 integration for OpenOffice.org, if available.
export SAL_USE_VCLPLUGIN=gtk

# Launch DBus if needed
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

export XDG_MENU_PREFIX="lde-"

# Start the LDE session
exec /usr/bin/ldeinit

