QT.ftp_private.VERSION = 5.0.0
QT.ftp_private.MAJOR_VERSION = 5
QT.ftp_private.MINOR_VERSION = 0
QT.ftp_private.PATCH_VERSION = 0
QT.ftp_private.name = QtFtp
QT.ftp_private.libs = $$QT_MODULE_LIB_BASE
QT.ftp_private.includes = $$QT_MODULE_INCLUDE_BASE/QtFtp/5.0.0 $$QT_MODULE_INCLUDE_BASE/QtFtp/5.0.0/QtFtp
QT.ftp_private.depends = ftp
QT.ftp_private.module_config = staticlib internal_module no_link
