Document: lde
Title: Debian lde Manual
Author: <insert document author here>
Abstract: This manual describes what lde is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lde/lde.sgml.gz

Format: postscript
Files: /usr/share/doc/lde/lde.ps.gz

Format: text
Files: /usr/share/doc/lde/lde.text.gz

Format: HTML
Index: /usr/share/doc/lde/html/index.html
Files: /usr/share/doc/lde/html/*.html
