######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 12 04:59:00 2014
######################################################################

TEMPLATE = app
TARGET = lootepad
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp

RESOURCES += \
    rc.qrc
